const KEY='df_command_os_v2';
let state=load();
let timer=null;let radioRecorder=null;let radioChunks=[];let radioStream=null;let unlockTimer=null;let unlockStart=0;let mapTimer=null;

function initial(){return{view:'home',role:'player',match:{name:'Operação Red Sand',status:'aguardando',seconds:0},player:{id:'DF-001',name:'DANI',team:'azul',class:'Assalto',status:'aguardando',radio:true,channel:'01'},teams:{azul:{name:'AZUL',active:12,total:12},vermelho:{name:'VERMELHO',active:12,total:12}},objectives:{alfa:{name:'Setor Alfa',control:'neutro'},bravo:{name:'Setor Bravo',control:'neutro'}},events:[]}}
function load(){try{const x=JSON.parse(localStorage.getItem(KEY));return x?merge(initial(),x):initial()}catch(e){return initial()}}
function merge(a,b){return{...a,...b,match:{...a.match,...(b.match||{})},player:{...a.player,...(b.player||{}),radio:!!(b.player?.radio??a.player.radio)},teams:{...a.teams,...(b.teams||{})},objectives:{...a.objectives,...(b.objectives||{})},events:Array.isArray(b.events)?b.events:[]}}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function log(type,text){state.events.unshift({time:new Date().toLocaleTimeString('pt-BR',{hour12:false}),type,text});state.events=state.events.slice(0,80);save()}
function statusLabel(s){return({aguardando:'AGUARDANDO',andamento:'EM ANDAMENTO',pausada:'PAUSADA',encerrada:'ENCERRADA'})[s]||String(s).toUpperCase()}
function show(view){state.view=view;document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));document.getElementById('screen-'+view)?.classList.add('active');document.querySelectorAll('[data-nav]').forEach(x=>x.classList.toggle('active',x.dataset.nav===view));save();render()}
function startTimer(){clearInterval(timer);timer=setInterval(()=>{if(state.match.status==='andamento'){state.match.seconds++;renderClock();save()}},1000)}
function stopTimer(){clearInterval(timer);timer=null}
function fmt(sec){return[Math.floor(sec/3600),Math.floor(sec/60)%60,sec%60].map(x=>String(x).padStart(2,'0')).join(':')}
function setMatch(s){if(s==='andamento')startTimer();else stopTimer();state.match.status=s;log('MATCH',`Partida: ${statusLabel(s)}`);render()}
function ready(){if(state.match.status!=='andamento'){toast('O comando ainda não iniciou a partida.');return}state.player.status='ativo';log('PLAYER','DANI entrou na simulação');show('tactical')}
function hit(){if(state.player.status!=='ativo'){toast('O teste de HIT exige estado ATIVO.');return}state.player.status='atingido';state.teams[state.player.team].active=Math.max(0,state.teams[state.player.team].active-1);log('HIT','Estado do jogador alterado para ATINGIDO');navigator.vibrate?.([120,70,180]);document.body.animate([{filter:'brightness(1)'},{filter:'brightness(1.55)'},{filter:'brightness(1)'}],{duration:260});lockPanel();render()}
function recover(){if(state.player.status!=='atingido')return;state.player.status='ativo';state.teams[state.player.team].active=Math.min(state.teams[state.player.team].total,state.teams[state.player.team].active+1);log('PLAYER','Estado do jogador restaurado para ATIVO');unlockPanel();render()}
function objectiveDemo(){const key=state.objectives.alfa.control==='neutro'?'alfa':'bravo';state.objectives[key].control='azul';log('OBJECTIVE',`${state.objectives[key].name} atualizado para AZUL`);render()}
function radio(){state.player.radio=!state.player.radio;log('RADIO',state.player.radio?'Canal online':'Canal offline');render()}
function openBriefing(){modal('BRIEFING',`<div class="card"><span class="eyebrow">MISSÃO DEMONSTRATIVA</span><h3>Capturar e manter Alfa e Bravo.</h3></div><div class="card"><span class="eyebrow">SISTEMA</span><p class="muted">O Command OS acompanha estados, objetivos, comunicação, eventos e módulos de teste em um único fluxo.</p></div><div class="card"><span class="eyebrow">MÓDULOS</span><p class="muted">Rádio · mapa simulado · câmera demonstrativa · estados · eventos · comando.</p></div><button class="primary" onclick="closeModal()">FECHAR</button>`)}
function openMap(){modal('MAPA — CAMPO SIMULADO',`<div class="map-modal"><div id="simMap" class="sim-map"><div class="map-field"></div><div class="map-center">VOCÊ</div></div><div class="map-legend"><span class="legend-item"><i style="background:#74a98a"></i>Pontos AZUIS</span><span class="legend-item"><i style="background:#bf625b"></i>Pontos VERMELHOS</span><span class="legend-item">Movimentação fictícia de teste</span></div><button class="primary" onclick="closeModal()">FECHAR MAPA</button></div>`);startMapSimulation('simMap',true)}
function startMapSimulation(id,modalMode=false){clearInterval(mapTimer);const el=document.getElementById(id);if(!el)return;const points=[];for(let i=0;i<12;i++){const dot=document.createElement('span');dot.className=`map-dot ${i<6?'blue':'red'}`;dot.dataset.x=18+Math.random()*64;dot.dataset.y=18+Math.random()*64;el.appendChild(dot);points.push(dot)}const step=()=>points.forEach(d=>{let x=parseFloat(d.dataset.x),y=parseFloat(d.dataset.y);x=Math.max(8,Math.min(92,x+(Math.random()-.5)*7));y=Math.max(8,Math.min(92,y+(Math.random()-.5)*7));d.dataset.x=x;d.dataset.y=y;d.style.left=x+'%';d.style.top=y+'%'});step();mapTimer=setInterval(()=>{if(document.getElementById(id))step();else clearInterval(mapTimer)},900)}
function openCamera(){modal('CÂMERA — TESTE VISUAL',`<div class="sim-camera"><div class="ball roll"></div></div><p class="camera-note muted">Simulação visual local. O objeto animado é uma bola de boliche usada apenas como elemento de teste de interface.</p><button class="primary" onclick="closeModal()">ENCERRAR TESTE</button>`)}
function openRadioTest(){modal('RÁDIO — TESTE DE VOZ',`<div class="radio-recorder"><div class="radio-status"><div><b>CANAL ${state.player.channel}</b><small class="muted" style="display:block;margin-top:4px">Comunicação sempre disponível no painel</small></div><span id="recDot" class="rec-dot"></span></div><div class="level"><span id="recLevel"></span></div><button id="recordBtn" class="primary">● COMEÇAR TESTE DE VOZ</button><audio id="recordedAudio" class="recorded-audio hidden" controls></audio><p id="recText" class="muted">Grave uma mensagem curta para testar captura, reprodução e retorno local.</p><button class="secondary" onclick="closeModal()">FECHAR</button></div>`);document.getElementById('recordBtn').onclick=toggleRecording}
async function toggleRecording(){const btn=document.getElementById('recordBtn');if(radioRecorder?.state==='recording'){radioRecorder.stop();return}try{if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder)throw new Error('unsupported');radioStream=await navigator.mediaDevices.getUserMedia({audio:true});radioChunks=[];radioRecorder=new MediaRecorder(radioStream);radioRecorder.ondataavailable=e=>e.data.size&&radioChunks.push(e.data);radioRecorder.onstop=()=>{const blob=new Blob(radioChunks,{type:radioRecorder.mimeType||'audio/webm'});const url=URL.createObjectURL(blob);const audio=document.getElementById('recordedAudio');audio.src=url;audio.classList.remove('hidden');document.getElementById('recText').textContent='Mensagem gravada. Toque em reproduzir para ouvir o teste local.';document.getElementById('recDot').classList.remove('recording');btn.textContent='● GRAVAR NOVAMENTE';radioStream?.getTracks().forEach(t=>t.stop());radioStream=null;log('RADIO','Teste de voz gravado localmente');render()};radioRecorder.start();document.getElementById('recDot').classList.add('recording');document.getElementById('recText').textContent='Gravando… fale normalmente como em uma comunicação de teste.';btn.textContent='■ PARAR GRAVAÇÃO';pulseLevel()}catch(e){document.getElementById('recText').textContent='O navegador bloqueou o microfone ou não oferece gravação neste dispositivo.'}}
function pulseLevel(){if(radioRecorder?.state!=='recording')return;const x=document.getElementById('recLevel');if(x)x.style.width=(12+Math.random()*78)+'%';requestAnimationFrame(pulseLevel)}
function openDev(){modal('DEV TEST',`<p class="muted">Ambiente de testes da interface.</p><div class="dev-options"><button class="primary" onclick="setRole('player')">👤 TESTAR COMO JOGADOR</button><button class="warning" onclick="setRole('command')">◈ TESTAR COMO COMANDO</button><button class="secondary" onclick="resetDemo()">↻ RESETAR DEMO</button></div><div class="card"><span class="eyebrow">ESTADO ATUAL</span><p>${statusLabel(state.match.status)} · ${state.player.status.toUpperCase()}</p></div>`)}
function setRole(role){state.role=role;save();closeModal();show(role==='command'?'command':'home')}
function resetDemo(){stopTimer();stopRadio();clearInterval(mapTimer);state=initial();save();closeModal();show('home')}
function stopRadio(){if(radioRecorder?.state==='recording')radioRecorder.stop();radioStream?.getTracks().forEach(t=>t.stop());radioStream=null;radioRecorder=null}
function closeModal(){stopRadio();clearInterval(mapTimer);document.getElementById('modalRoot').innerHTML=''}
function modal(title,body){closeModal();document.getElementById('modalRoot').innerHTML=`<div class="modal-backdrop" onclick="if(event.target===this)closeModal()"><div class="modal"><div class="modal-head"><h2>${title}</h2><button onclick="closeModal()">✕</button></div><div class="modal-body">${body}</div></div></div>`}
function toast(text){const x=document.createElement('div');x.textContent=text;x.style.cssText='position:fixed;left:50%;bottom:95px;transform:translateX(-50%);z-index:200;background:#162019;border:1px solid #617653;color:#edf1e9;padding:12px 15px;border-radius:10px;font-size:.72rem;box-shadow:0 8px 30px #000';document.body.appendChild(x);setTimeout(()=>x.remove(),2200)}
function renderClock(){const x=document.getElementById('gameClock');if(x)x.textContent=fmt(state.match.seconds)}
function render(){const q=id=>document.getElementById(id);q('headerRole').textContent=state.role==='command'?'COMANDO':'JOGADOR';q('headerMatch').textContent=statusLabel(state.match.status);q('matchName').textContent=state.match.name;q('homeStatus').textContent=statusLabel(state.match.status);q('playerName').textContent=state.player.name;q('playerTeam').textContent=state.teams[state.player.team].name;q('playerId').textContent=state.player.id;q('playerClass').value=state.player.class;q('radioBadge').textContent=state.player.radio?`● RÁDIO CH ${state.player.channel}`:'● RÁDIO OFFLINE';q('readyState').textContent=state.match.status==='andamento'?'Partida em andamento':'Aguardando partida';q('readyButton').disabled=state.match.status!=='andamento';q('tacticalMatch').textContent=state.match.name.toUpperCase();q('tacticalStatus').textContent=state.player.status==='atingido'?'HIT':statusLabel(state.match.status);q('tacticalStatus').className='pill '+(state.player.status==='atingido'?'danger':state.match.status==='andamento'?'success':'warning');renderClock();const active=state.player.status==='ativo',hitState=state.player.status==='atingido';q('playerStateIcon').textContent=active?'✓':hitState?'!':'•';q('playerStateTitle').textContent=active?'ATIVO':hitState?'ATINGIDO':'AGUARDANDO';q('playerStateDesc').textContent=active?'Sistema operacional.':hitState?'Estado alterado pelo teste.':'Aguardando entrada na partida.';q('hitButton').textContent=hitState?'RESTAURAR ESTADO':'REGISTRAR HIT';q('hitButton').onclick=hitState?recover:hit;q('missionProgress').style.width=(Object.values(state.objectives).filter(o=>o.control==='azul').length/2*100)+'%';q('missionText').textContent=`${Object.values(state.objectives).filter(o=>o.control!=='neutro').length} de 2 setores registrados`;q('commandStatus').textContent=statusLabel(state.match.status);q('blueCount').textContent=state.teams.azul.active;q('redCount').textContent=state.teams.vermelho.active;q('objectiveCount').textContent=Object.values(state.objectives).filter(o=>o.control!=='neutro').length+'/2';q('eventCount').textContent=state.events.length;const start=q('startMatch'),pause=q('pauseMatch'),resume=q('resumeMatch'),end=q('endMatch');start.classList.toggle('hidden',state.match.status!=='aguardando');pause.classList.toggle('hidden',state.match.status!=='andamento');resume.classList.toggle('hidden',state.match.status!=='pausada');end.classList.toggle('hidden',!['andamento','pausada'].includes(state.match.status));q('objectives').innerHTML=Object.values(state.objectives).map(o=>`<div class="objective ${o.control==='azul'?'blue':''}"><div><b>${o.name}</b><small> · ${o.control==='neutro'?'NEUTRO':o.control.toUpperCase()}</small></div><span>${o.control==='neutro'?'○':'●'}</span></div>`).join('');q('logs').innerHTML=state.events.length?state.events.map(e=>`<div class="log"><time>${e.time}</time><b>${e.type}</b> ${e.text}</div>`).join(''):'<span class="muted">Nenhum evento registrado.</span>';drawCommandMap()}
function drawCommandMap(){const el=document.getElementById('commandMap');if(!el)return;el.innerHTML='<div class="map-field"></div><div class="map-center">CENTRO</div>';for(let i=0;i<8;i++){const d=document.createElement('span');d.className=`map-dot ${i<4?'blue':'red'}`;d.style.left=(15+Math.random()*70)+'%';d.style.top=(15+Math.random()*70)+'%';el.appendChild(d)}}
function bind(){document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>show(b.dataset.nav));document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>{const a=b.dataset.action;({home:()=>show('home'),prepare:()=>show('prepare'),tactical:()=>show('tactical'),command:()=>show('command'),playerView:()=>show('tactical'),briefing:openBriefing,map:openMap,camera:openCamera,radioTest:openRadioTest,dev:openDev,ready,hit,start:()=>setMatch('andamento'),pause:()=>setMatch('pausada'),resume:()=>setMatch('andamento'),end:()=>setMatch('encerrada'),objectiveDemo,clearLogs:()=>{state.events=[];save();render()}}[a]?.() )});document.getElementById('playerClass').onchange=e=>{state.player.class=e.target.value;log('PLAYER',`Classe alterada: ${e.target.value}`);render()}}
function unlockPanel(){document.getElementById('touchGuard')?.classList.remove('visible')}
function lockPanel(){document.getElementById('touchGuard')?.classList.add('visible')}
function initTouchGuard(){const guard=document.getElementById('touchGuard');if(!guard)return;const begin=e=>{e.preventDefault();unlockStart=performance.now();const bar=guard.querySelector('.unlock-track span');unlockTimer=setInterval(()=>{const p=Math.min(100,(performance.now()-unlockStart)/1200*100);if(bar)bar.style.width=p+'%';if(p>=100){clearInterval(unlockTimer);unlockPanel();navigator.vibrate?.(30)}},30)};const cancel=()=>{clearInterval(unlockTimer);const bar=guard.querySelector('.unlock-track span');if(bar)bar.style.width='0'};guard.addEventListener('pointerdown',begin);guard.addEventListener('pointerup',cancel);guard.addEventListener('pointercancel',cancel);guard.addEventListener('pointerleave',cancel)}
function init(){bind();initTouchGuard();startTimer();render();lockPanel();}
window.addEventListener('beforeunload',()=>{stopRadio();stopTimer()});init();
