const KEY='df_player_terminal_v3';
const GOOGLE_MAPS_API_KEY='COLOQUE_SUA_CHAVE_GOOGLE_MAPS_AQUI';
let state=load();let timer=null;let radioRecorder=null;let radioStream=null;let radioChunks=[];let unlockTimer=null;let unlockStart=0;let watchId=null;let googleMap=null;let playerMarker=null;let pttDown=false;
function initial(){return{view:'home',match:{name:'Operação Red Sand',status:'aguardando',seconds:0},player:{id:'DF-001',name:'DANI',team:'azul',class:'Assalto',status:'aguardando',radio:true,channel:'01',radioVolume:70,briefingAck:false,participation:false,selfie:null},gps:{lat:null,lng:null,accuracy:null,ready:false},objectives:{alfa:{name:'Setor Alfa',control:'neutro'},bravo:{name:'Setor Bravo',control:'neutro'}},events:[]}}
function load(){try{const x=JSON.parse(localStorage.getItem(KEY));return x?merge(initial(),x):initial()}catch(e){return initial()}}
function merge(a,b){return{...a,...b,match:{...a.match,...(b.match||{})},player:{...a.player,...(b.player||{})},gps:{...a.gps,...(b.gps||{})},objectives:{...a.objectives,...(b.objectives||{})},events:Array.isArray(b.events)?b.events:[]}}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function log(type,text){state.events.unshift({time:new Date().toLocaleTimeString('pt-BR',{hour12:false}),type,text});state.events=state.events.slice(0,100);save()}
function show(view){if(state.match.status==='andamento'&&state.player.participation&&view!=='tactical')return;state.view=view;document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));document.getElementById('screen-'+view)?.classList.add('active');save();render()}
function fmt(sec){return[Math.floor(sec/3600),Math.floor(sec/60)%60,sec%60].map(x=>String(x).padStart(2,'0')).join(':')}
function startTimer(){clearInterval(timer);timer=setInterval(()=>{if(state.match.status==='andamento'){state.match.seconds++;const x=document.getElementById('gameClock');if(x)x.textContent=fmt(state.match.seconds);save()}},1000)}
function openPrepTab(tab){document.querySelectorAll('.prep-tab').forEach(x=>x.classList.toggle('active',x.dataset.prep===tab));document.querySelectorAll('.prep-pane').forEach(x=>x.classList.toggle('active',x.id==='prep-'+tab))}
function briefingChanged(){state.player.briefingAck=!!document.getElementById('briefingAck')?.checked;save();updateParticipationButton()}
function updateParticipationButton(){const b=document.getElementById('confirmParticipation');if(b)b.disabled=!(state.player.briefingAck&&state.player.selfie)}
async function captureSelfie(){const preview=document.getElementById('selfiePreview');try{if(!navigator.mediaDevices?.getUserMedia)throw 0;const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user'},audio:false});const video=document.createElement('video');video.autoplay=true;video.playsInline=true;video.srcObject=stream;preview.classList.remove('hidden');preview.innerHTML='';preview.appendChild(video);const snap=document.createElement('button');snap.className='wide primary';snap.textContent='CAPTURAR';preview.appendChild(snap);snap.onclick=()=>{const canvas=document.createElement('canvas');canvas.width=720;canvas.height=720;const ctx=canvas.getContext('2d');const size=Math.min(video.videoWidth,video.videoHeight);ctx.drawImage(video,(video.videoWidth-size)/2,(video.videoHeight-size)/2,size,size,0,0,720,720);const now=new Date();ctx.fillStyle='rgba(0,0,0,.68)';ctx.fillRect(0,650,720,70);ctx.fillStyle='#fff';ctx.font='22px monospace';ctx.fillText(now.toLocaleString('pt-BR'),24,678);ctx.font='17px monospace';ctx.fillText(state.gps.ready?`${state.gps.lat.toFixed(6)}, ${state.gps.lng.toFixed(6)}`:'LOCALIZAÇÃO NÃO DISPONÍVEL',24,705);state.player.selfie={data:canvas.toDataURL('image/jpeg',.78),timestamp:now.toISOString(),lat:state.gps.lat,lng:state.gps.lng};stream.getTracks().forEach(t=>t.stop());preview.innerHTML=`<img src="${state.player.selfie.data}" alt="Registro de presença"><span>REGISTRO CAPTURADO · ${now.toLocaleTimeString('pt-BR',{hour12:false})}</span>`;save();log('PRESENÇA','Selfie de presença registrada');updateParticipationButton()}}catch(e){toast('Câmera indisponível ou permissão negada.')}}
function confirmParticipation(){if(!(state.player.briefingAck&&state.player.selfie)){toast('Leia o briefing e registre a selfie antes de confirmar.');return}state.player.participation=true;state.player.status='aguardando';log('PRESENÇA','Participação confirmada');show('waiting');startGps();render()}
function startMatch(){state.match.status='andamento';state.match.seconds=0;state.player.status=state.player.participation?'ativo':'aguardando';log('MATCH','Organizador iniciou a partida');if(state.player.participation){show('tactical');lockPanel()}render()}
function hit(){if(state.player.status!=='ativo'){toast('O registro exige o estado ATIVO.');return}state.player.status='atingido';log('HIT','Estado do jogador alterado para ATINGIDO');navigator.vibrate?.([120,70,180]);document.body.animate([{filter:'brightness(1)'},{filter:'brightness(1.35)'},{filter:'brightness(1)'}],{duration:260});lockPanel();render()}
function recover(){if(state.player.status!=='atingido')return;state.player.status='ativo';log('PLAYER','Estado restaurado para ATIVO');unlockPanel();render()}
function toggleRadio(){state.player.radio=!state.player.radio;log('RADIO',state.player.radio?'Rádio ligado':'Rádio desligado');render()}
function setChannel(v){state.player.channel=v;log('RADIO',`Frequência alterada para CH ${v}`);render()}
function setVolume(v){state.player.radioVolume=Number(v);save()}
async function startPtt(){if(!state.player.radio){toast('O rádio está desligado.');return}if(pttDown)return;pttDown=true;const btn=document.getElementById('radioPtt');btn?.classList.add('transmitting');if(btn)btn.textContent='TRANSMITINDO…';document.getElementById('radioTx')?.replaceChildren(document.createTextNode('TRANSMITINDO'));try{if(navigator.mediaDevices?.getUserMedia&&window.MediaRecorder){radioStream=await navigator.mediaDevices.getUserMedia({audio:true});radioChunks=[];radioRecorder=new MediaRecorder(radioStream);radioRecorder.ondataavailable=e=>e.data.size&&radioChunks.push(e.data);radioRecorder.onstop=()=>{if(radioChunks.length)log('RADIO',`Transmissão local · CH ${state.player.channel}`);radioStream?.getTracks().forEach(t=>t.stop());radioStream=null;radioRecorder=null};radioRecorder.start()}else log('RADIO',`PTT simulado · CH ${state.player.channel}`)}catch(e){log('RADIO',`PTT simulado · CH ${state.player.channel}`)}}
function stopPtt(){if(!pttDown)return;pttDown=false;if(radioRecorder?.state==='recording')radioRecorder.stop();radioStream?.getTracks().forEach(t=>t.stop());radioStream=null;radioRecorder=null;const btn=document.getElementById('radioPtt');btn?.classList.remove('transmitting');if(btn)btn.textContent='SEGURE PARA FALAR';document.getElementById('radioTx')?.replaceChildren(document.createTextNode('PRONTO'))}
function openInstructions(){modal('BRIEFING E REGRAS',`<div class="card"><span class="eyebrow">PARTIDA CONFIGURADA</span><h3>Operação Red Sand</h3><p class="muted">As regras exibidas aqui são as configuradas previamente pelo organizador.</p></div><div class="rule-card"><b>Responsabilidade</b><p>Você confirmou ciência das regras apresentadas antes da participação.</p></div><button class="primary" onclick="closeModal()">FECHAR</button>`)}
function modal(title,body){closeModal();document.getElementById('modalRoot').innerHTML=`<div class="modal-backdrop" onclick="if(event.target===this)closeModal()"><div class="modal"><div class="modal-head"><h2>${title}</h2><button onclick="closeModal()">✕</button></div><div class="modal-body">${body}</div></div></div>`}
function closeModal(){stopPtt();document.getElementById('modalRoot').innerHTML=''}
function toast(text){const x=document.createElement('div');x.className='app-toast';x.textContent=text;document.body.appendChild(x);setTimeout(()=>x.remove(),2400)}
function lockPanel(){document.getElementById('touchGuard')?.classList.add('visible')}
function unlockPanel(){document.getElementById('touchGuard')?.classList.remove('visible')}
function initTouchGuard(){const guard=document.getElementById('touchGuard');if(!guard)return;const begin=e=>{if(state.match.status!=='andamento')return;e.preventDefault();unlockStart=performance.now();const bar=guard.querySelector('.unlock-track span');unlockTimer=setInterval(()=>{const p=Math.min(100,(performance.now()-unlockStart)/1200*100);if(bar)bar.style.width=p+'%';if(p>=100){clearInterval(unlockTimer);unlockPanel();navigator.vibrate?.(30)}},30)};const cancel=()=>{clearInterval(unlockTimer);const bar=guard.querySelector('.unlock-track span');if(bar)bar.style.width='0'};guard.addEventListener('pointerdown',begin);['pointerup','pointercancel','pointerleave'].forEach(ev=>guard.addEventListener(ev,cancel))}
function startGps(){if(!navigator.geolocation)return;clearWatch();watchId=navigator.geolocation.watchPosition(pos=>{state.gps={lat:pos.coords.latitude,lng:pos.coords.longitude,accuracy:pos.coords.accuracy,ready:true};save();renderGps();updateGooglePosition()},()=>{state.gps.ready=false;renderGps()},{enableHighAccuracy:true,maximumAge:3000,timeout:10000})}
function clearWatch(){if(watchId!==null){navigator.geolocation.clearWatch(watchId);watchId=null}}
function renderGps(){const s=document.getElementById('gpsStatus'),c=document.getElementById('gpsCoords'),a=document.getElementById('gpsAccuracy');if(!s||!c||!a)return;if(state.gps.ready){s.textContent='● GPS ATIVO';c.textContent=`${state.gps.lat.toFixed(6)}, ${state.gps.lng.toFixed(6)}`;a.textContent=`PRECISÃO ±${Math.round(state.gps.accuracy)} M`}else{s.textContent='● GPS AGUARDANDO';c.textContent='LOCALIZAÇÃO NÃO DISPONÍVEL';a.textContent='PRECISÃO —'}}
function loadGoogleMaps(){const el=document.getElementById('googleMap');if(!el)return;if(window.google?.maps){initGoogleMap();return}if(GOOGLE_MAPS_API_KEY.includes('COLOQUE_')){el.innerHTML='<div class="map-loading"><b>GOOGLE MAPS</b><small>Configure a chave da Google Maps JavaScript API em app.js para ativar o mapa.</small></div>';return}const s=document.createElement('script');s.src=`https://maps.googleapis.com/maps/api/js?key=${encodeURIComponent(GOOGLE_MAPS_API_KEY)}&callback=initGoogleMap`;s.async=true;s.defer=true;document.head.appendChild(s)}
window.initGoogleMap=initGoogleMap;
function initGoogleMap(){const el=document.getElementById('googleMap');if(!el||!window.google?.maps)return;const fallback={lat:-19.9167,lng:-43.9345};const center=state.gps.ready?{lat:state.gps.lat,lng:state.gps.lng}:fallback;googleMap=new google.maps.Map(el,{center,zoom:17,mapTypeId:'satellite',disableDefaultUI:true,zoomControl:true,gestureHandling:'greedy'});playerMarker=new google.maps.Marker({position:center,map:googleMap,title:'Você',label:{text:'VOCÊ',color:'#ffffff',fontSize:'10px',fontWeight:'700'}});if(state.gps.ready)googleMap.setCenter(center)}
function updateGooglePosition(){if(!googleMap||!state.gps.ready)return;const p={lat:state.gps.lat,lng:state.gps.lng};playerMarker?.setPosition(p);googleMap.setCenter(p)}
function render(){const q=id=>document.getElementById(id);q('headerMatch').textContent=state.match.status==='andamento'?'EM ANDAMENTO':state.player.participation?'AGUARDANDO INÍCIO':'PREPARAÇÃO';q('homePlayerName').textContent=state.player.name;q('homeIdentity').textContent=`${state.player.id} · ${state.player.team.toUpperCase()} · ${state.player.class.toUpperCase()}`;q('profileName').textContent=state.player.name;q('profileMeta').textContent=`${state.player.id} · ${state.player.team.toUpperCase()}`;q('profileClass').textContent=state.player.class.toUpperCase();q('profileStatus').textContent=state.player.status.toUpperCase();q('profileRadio').textContent=state.player.radio?`CH ${state.player.channel}`:'DESLIGADO';q('briefingAck').checked=!!state.player.briefingAck;updateParticipationButton();q('waitingMatchStatus').textContent=state.match.status==='andamento'?'PARTIDA INICIADA':'AGUARDANDO ORGANIZADOR';q('tacticalMatch').textContent=state.match.name.toUpperCase();q('tacticalState').textContent=state.player.status==='atingido'?'ATINGIDO':'ATIVO';q('radioStatus').textContent=state.player.radio?`LIGADO · CH ${state.player.channel}`:'DESLIGADO';q('radioPower').textContent=state.player.radio?'DESLIGAR':'LIGAR';q('radioChannel').value=state.player.channel;q('radioVolume').value=state.player.radioVolume;q('playerStateTitle').textContent=state.player.status==='ativo'?'ATIVO':state.player.status==='atingido'?'ATINGIDO':'AGUARDANDO';q('playerStateDesc').textContent=state.player.status==='atingido'?'Estado registrado.':'Partida em andamento.';q('hitButton').textContent=state.player.status==='atingido'?'ESTADO REGISTRADO':'REGISTRAR HIT';q('missionProgress').style.width=(Object.values(state.objectives).filter(o=>o.control==='azul').length/2*100)+'%';q('missionText').textContent=`${Object.values(state.objectives).filter(o=>o.control!=='neutro').length} de 2 setores registrados`;const p=document.getElementById('radioVolume');if(p)p.value=state.player.radioVolume;const t=document.getElementById('gameClock');if(t)t.textContent=fmt(state.match.seconds);renderGps();if(state.match.status==='andamento'&&state.player.participation)lockPanel()}
function bind(){document.querySelectorAll('[data-prep]').forEach(b=>b.onclick=()=>openPrepTab(b.dataset.prep));document.getElementById('briefingAck').onchange=briefingChanged;document.getElementById('selfieButton').onclick=captureSelfie;document.getElementById('confirmParticipation').onclick=confirmParticipation;document.getElementById('radioPower').onclick=toggleRadio;document.getElementById('radioChannel').onchange=e=>setChannel(e.target.value);document.getElementById('radioVolume').oninput=e=>setVolume(e.target.value);const p=document.getElementById('radioPtt');p.addEventListener('pointerdown',e=>{e.preventDefault();startPtt()});['pointerup','pointercancel','pointerleave'].forEach(ev=>p.addEventListener(ev,stopPtt));document.getElementById('hitButton').onclick=()=>state.player.status==='atingido'?recover():hit;document.querySelector('[data-action="instructions"]').onclick=openInstructions)}
function init(){bind();initTouchGuard();startTimer();if(state.player.participation)startGps();render();loadGoogleMaps()}
window.startMatchFromOrganizer=startMatch;
window.addEventListener('beforeunload',()=>{clearWatch();stopPtt();clearInterval(timer)});
init();